{'btc_usdt': 'Bitcoin', 'bch_usdt': 'BCH', 'eth_usdt':'Ethereum', 'etc_usdt':'Ethereum Classic', 'qtum_usdt':'QTUM',
 'ltc_usdt':'LiteCoin', 'dash_usdt':'Dash', 'zec_usdt':'ZCash', 'btm_usdt':'Bytom', 'eos_usdt':'EOS', 'req_usdt':'Request',
 'snt_usdt':'Status', 'omg_usdt':'OmiseGo', 'pay_usdt':'TenX', 'cvc_usdt':'Civic', 'zrx_usdt':'0xProject', 'tnt_usdt':'Tierion',
 'xmr_usdt':'Monero', 'xrp_usdt':'Ripple', 'doge_usdt':'DogeCoin', 'bat_usdt':'BasicAttentionToken', 'pst_usdt':'Primas',
 'btg_usdt':'BTG', 'dpy_usdt':'Delphy', 'lrc_usdt':'Loopring', 'storj_usdt':'Storj', 'rdn_usdt':'Raiden', 'stx_usdt':'Stox',
 'knc_usdt':'Kyber', 'link_usdt':'ChainLink', 'cdt_usdt':'CoinDash', 'ae_usdt':'', 'ae_eth':'Aeternity', 'cdt_eth':'CoinDash',
 'rdn_eth':'Raiden', 'stx_eth':'Stox', 'knc_eth':'Kyber', 'link_eth':'ChainLink', 'req_eth':'Request', 'rcn_eth':'Ripio', 'trx_eth':'Tron',
 'arn_eth':'Aeron', 'kick_eth':'KickCoin', 'bnt_eth':'Bounty0x', 'ven_eth':'Vechain', 'mco_eth':'Monaco', 'fun_eth':'FunFair',
 'data_eth':'Streamr', 'rlc_eth':'iExec', 'zsc_eth':'ZeusShield', 'wings_eth':'Wings', 'ctr_eth':'Centra', 'mda_eth':'Moeda',
 'rcn_usdt':'Ripio', 'trx_usdt':'Tron', 'kick_usdt':'KickCoin', 'ven_usdt':'Vechain', 'mco_usdt':'Monaco', 'fun_usdt':'FunFair',
 'data_usdt':'Streamr', 'zsc_usdt':'ZeusShield', 'ctr_usdt':'Centra', 'mda_usdt':'Moeda', 'xtz_usdt':'Tezos', 'gnt_usdt':'Golem',
 'gnt_eth':'Golem', 'ost_usdt':'Simple Token', 'ost_eth':'Simple Token', 'xlm_usdt':'Stellar', 'xlm_eth':'Stellar', 'xlm_btc':'Stellar',
 'mobi_usdt':'Mobius', 'mobi_eth':'Mobius', 'mobi_btc':'Mobius', 'ocn_usdt':'OCOIN', 'ocn_eth':'OCOIN', 'ocn_btc':'OCOIN',
 'zpt_usdt':'Zeepin', 'zpt_eth':'Zeepin', 'zpt_btc':'Zeepin', 'cofi_usdt':'CoinFi', 'cofi_eth':'CoinFi', 'jnt_usdt':'JibrelNetwork',
 'jnt_eth':'JibrelNetwork', 'jnt_btc':'JibrelNetwork', 'blz_usdt':'Bluzelle', 'blz_eth':'Bluzelle', 'gxs_usdt':'GXShares', 'gxs_btc':'GXShares',
 'mtn_usdt':'Medicalchain', 'mtn_eth':'Medicalchain', 'ruff_usdt':'RuffChain', 'ruff_eth':'RuffChain', 'ruff_btc':'RuffChain', 'tnc_usdt':'Trinity',
 'tnc_eth':'Trinity', 'tnc_btc':'Trinity', 'zil_usdt':'Zilliqa', 'zil_eth':'Zilliqa', 'tio_usdt':'Trade.io', 'tio_eth':'Trade.io',
 'bto_usdt':'Bottos', 'bto_eth':'Bottos', 'theta_usdt':'Theta', 'theta_eth':'Theta', 'ddd_usdt':'Scry', 'ddd_eth':'Scry', 'ddd_btc':'Scry',
 'mkr_usdt':'MakerDAO', 'mkr_eth':'MakerDAO', 'dai_usdt':'Dai', 'smt_usdt':'SmartMesh', 'smt_eth':'SmartMesh', 'mdt_usdt':'MeasurableData',
 'mdt_eth':'MeasurableData', 'mdt_btc':'MeasurableData', 'mana_usdt':'Decentraland', 'mana_eth':'Decentraland', 'lun_usdt':'Lunyr',
 'lun_eth':'Lunyr', 'salt_usdt':'Salt', 'salt_eth':'Salt', 'fuel_usdt':'EtherParty', 'fuel_eth':'EtherParty', 'elf_usdt':'aelf', 'elf_eth':'aelf',
 'drgn_usdt':'DragonChain', 'drgn_eth':'DragonChain', 'gtc_usdt':'Game.com', 'gtc_eth':'Game.com', 'gtc_btc':'Game.com', 'qlc_usdt':'Qlink',
 'qlc_btc':'Qlink', 'qlc_eth':'Qlink', 'dbc_usdt':'DeepBrain', 'dbc_btc':'DeepBrain', 'dbc_eth':'DeepBrain', 'bnty_usdt':'Bounty0x',
 'bnty_eth':'Bounty0x', 'lend_usdt':'ETHLen', 'lend_eth':'ETHLen', 'icx_usdt':'ICON', 'icx_eth':'ICON', 'btf_usdt':'BTF', 'btf_btc':'BTF',
 'ada_usdt':'Cardano', 'ada_btc':'Cardano', 'lsk_usdt':'Lisk', 'lsk_btc':'Lisk', 'waves_usdt':'Waves', 'waves_btc':'Waves', 'bifi_usdt':'BitcoinFile',
 'bifi_btc':'BitcoinFile', 'mds_eth':'MediShares', 'mds_usdt':'MediShares', 'dgd_usdt':'DigixDAO', 'dgd_eth':'DigixDAO', 'qash_usdt':'LIQUID',
 'qash_eth':'LIQUID', 'qash_btc':'LIQUID', 'powr_usdt':'PowerLedger', 'powr_eth':'PowerLedger', 'powr_btc':'PowerLedger', 'fil_usdt':'IPFS 6-month',
 'bcd_usdt':'BCD', 'bcd_btc':'BCD', 'sbtc_usdt':'SuperBitcoin', 'sbtc_btc':'SuperBitcoin', 'god_usdt':'BitcoinGod', 'god_btc':'BitcoinGod',
 'bcx_usdt':'BCX', 'bcx_btc':'BCX', 'hsr_usdt':'HShare', 'hsr_btc':'HShare', 'hsr_eth':'HShare', 'qsp_usdt':'Quantstamp', 'qsp_eth':'Quantstamp',
 'ink_btc':'Ink', 'ink_usdt':'Ink', 'ink_eth':'Ink', 'ink_qtum':'Ink', 'med_qtum':'MediBloc', 'med_eth':'MediBloc', 'med_usdt':'MediBloc',
 'bot_qtum':'Bodhi', 'bot_usdt':'Bodhi', 'bot_eth':'Bodhi', 'qbt_qtum':'Qbao', 'qbt_eth':'Qbao', 'qbt_usdt':'Qbao', 'tsl_qtum':'Energo',
 'tsl_usdt':'Energo', 'gnx_usdt':'GenaroNetwork', 'gnx_eth':'GenaroNetwork', 'neo_usdt':'Neo', 'gas_usdt':'Gas', 'neo_btc':'Neo', 'gas_btc':'Gas',
 'iota_usdt':'IOTA', 'iota_btc':'IOTA', 'nas_usdt':'Nebulas', 'nas_eth':'Nebulas', 'nas_btc':'Nebulas', 'eth_btc':'Ethereum', 'etc_btc':'Ethereum Classic',
 'etc_eth':'Ethereum Classic', 'zec_btc':'ZCash', 'dash_btc':'Dash', 'ltc_btc':'Litecoin', 'bch_btc':'BCH', 'btg_btc':'BTG', 'qtum_btc':'Qtum',
 'qtum_eth':'Qtum', 'xrp_btc':'Ripple', 'doge_btc':'DogeCoin', 'xmr_btc':'Monero', 'zrx_btc':'0xProject', 'zrx_eth':'0xProject', 'dnt_eth':'district0x',
 'dpy_eth':'delphy', 'oax_eth':'OpenANX', 'rep_eth':'Augur', 'lrc_eth':'Loopring', 'lrc_btc':'Loopring', 'pst_eth':'Primas', 'bcdn_eth':'BlockCDN',
 'bcdn_usdt':'BlockCDN', 'tnt_eth':'Tierion', 'snt_eth':'Status', 'snt_btc':'Status', 'btm_eth':'Bytom', 'btm_btc':'Bytom', 'llt_eth':'LLToken',
 'llt_usdt':'LLToken', 'snet_eth':'Snetwork', 'snet_usdt':'Snetwork', 'omg_eth':'OmiseGo', 'omg_btc':'OmiseGo', 'pay_eth':'TenX', 'pay_btc':'TenX',
 'bat_eth':'BasicAttentionToken', 'bat_btc':'BasicAttentionToken', 'cvc_eth':'Civic', 'storj_eth':'Storj', 'storj_btc':'Storj',
 'eos_eth':'EOS', 'eos_btc':'EOS', 'bts_usdt':'BitShares', 'bts_btc':'BitShares'}
